services:
  - type: web
    name: informal-workers-api
    runtime: python
    plan: free
    rootDir: Informal_Workers_FastAPI_Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

